import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kanit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1 className="text-center text-amber-300 text-2xl">SHONEXT APP</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
